### ISSUE TITLE
df_acts has NaN values

### ISSUE THREAD

**Issue by dreesm** [dodo-saba/fit2gpx#2]
Was getting error below. Somewhere in the 'activites.csv' file there are NaN values that cause an issue. Not sure what the best way to fix it is, but simply adding a line 'df_acts = df_acts.fillna('')' worked for me. 

Traceback (most recent call last):
  File "gpxconvert.py", line 20, in <module>
    strava_conv.strava_fit_to_gpx()
  File "env/lib/python3.8/site-packages/fit2gpx.py", line 341, in strava_fit_to_gpx
    md = df_acts.loc[df_acts['Filename'].str.contains(f_activity)].iloc[0, :].to_dict()
  File "env/lib/python3.8/site-packages/pandas/core/indexing.py", line 967, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "env/lib/python3.8/site-packages/pandas/core/indexing.py", line 1181, in _getitem_axis
    elif com.is_bool_indexer(key):
  File "/env/lib/python3.8/site-packages/pandas/core/common.py", line 144, in is_bool_indexer
    raise ValueError(na_msg)
ValueError: Cannot mask with non-boolean array containing NA / NaN values

**Comment by CDunhill** [comment]
Not just me then?!

Sorry, where do you add that _df_acts = df_acts.fillna('')_ line?
